[project]
name = "mod7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.1.4",
    "pycaret>=3.3.2",
    "streamlit>=1.51.0",
    "streamlit-extras>=0.7.8",
]
